/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_angelvasquez;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Angel
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ad_Maestro = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sp_edad = new javax.swing.JSpinner();
        sal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        menu_popup = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        Elimniar = new javax.swing.JMenuItem();
        ad_clases = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        secion = new javax.swing.JTextField();
        ed = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        salon = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        yes = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        menu_MAE = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        gfd = new javax.swing.JMenuItem();
        mcla = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Estudiantes = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lMaestros = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Clases = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jLabel6.setText("Nombre");

        jLabel7.setText("Apellido");

        jLabel8.setText("Salario");

        jLabel9.setText("Edad");

        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ad_MaestroLayout = new javax.swing.GroupLayout(ad_Maestro.getContentPane());
        ad_Maestro.getContentPane().setLayout(ad_MaestroLayout);
        ad_MaestroLayout.setHorizontalGroup(
            ad_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ad_MaestroLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(ad_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ad_MaestroLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(sal, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                    .addGroup(ad_MaestroLayout.createSequentialGroup()
                        .addGroup(ad_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ad_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(apellido)))
                    .addGroup(ad_MaestroLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(ad_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        ad_MaestroLayout.setVerticalGroup(
            ad_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ad_MaestroLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(ad_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(ad_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(ad_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ad_MaestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );

        Modificar.setText("Modificar");
        menu_popup.add(Modificar);

        Elimniar.setText("Eliminar");
        Elimniar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElimniarActionPerformed(evt);
            }
        });
        menu_popup.add(Elimniar);

        jLabel10.setText("Nombre");

        jLabel11.setText("Seccion");

        jLabel12.setText("Edificio");

        jLabel13.setText("Salon");

        jLabel14.setText("Aire acondicionado");

        yes.setText("Si tiene");

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ad_clasesLayout = new javax.swing.GroupLayout(ad_clases.getContentPane());
        ad_clases.getContentPane().setLayout(ad_clasesLayout);
        ad_clasesLayout.setHorizontalGroup(
            ad_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ad_clasesLayout.createSequentialGroup()
                .addGroup(ad_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ad_clasesLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(ad_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ad_clasesLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(yes))
                            .addGroup(ad_clasesLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(secion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ad_clasesLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ad_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(ad_clasesLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(salon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ad_clasesLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addComponent(ed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(ad_clasesLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButton2)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        ad_clasesLayout.setVerticalGroup(
            ad_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ad_clasesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(ad_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ad_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(secion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(ad_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ad_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(salon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(ad_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(yes))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        menu_MAE.add(Eliminar);

        gfd.setText("Modificar");
        menu_MAE.add(gfd);

        jMenuItem4.setText("Eliminar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mcla.add(jMenuItem4);

        jMenuItem5.setText("jMenuItem5");
        mcla.add(jMenuItem5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Carreras");
        jTree2.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTree2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manejo de Datos ");

        jLabel2.setText("Arbol");

        Estudiantes.setModel(new DefaultListModel());
        Estudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstudiantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Estudiantes);

        jLabel3.setText("Estudiantes");

        lMaestros.setModel(new DefaultListModel());
        lMaestros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lMaestrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lMaestros);

        jLabel4.setText("Maestros");

        Clases.setModel(new DefaultListModel());
        Clases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClasesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Clases);

        jLabel5.setText("Clases");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(58, 58, 58))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jMenu1.setText("Agregar");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Agregar Estudiante");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Agregar Clases");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Agregar Maestros");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String nombre, apellido, carrera = "",tc="";
        int edad = 0,op,op2;
        boolean val = false;
        char genero;
        nombre = JOptionPane.showInputDialog("Ingrese nombre");
        apellido = JOptionPane.showInputDialog("Ingrese Apellido");
        genero = JOptionPane.showInputDialog("m Hombre o f Mujer").charAt(0);
        while (genero != 'm' && genero != 'M' && genero != 'f' && genero != 'm') {
            genero = JOptionPane.showInputDialog("m Hombre o f Mujer").charAt(0);
        }
        while (val == false) {
            try {
              edad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese su edad"));
              val = true;
            }
            catch(Exception e)
            {
              JOptionPane.showMessageDialog(null, "Dato no valido");
            }
        }
       while(val == true)
       {
           try
           {
             
             op=Integer.parseInt(JOptionPane.showInputDialog("1. Licenciaturas\n2.Ingenierías\n3.Ciencias de la Salud\nIngrese una opcion"));
               while (op>3 || op<=0) {
                   op=Integer.parseInt(JOptionPane.showInputDialog("1. Licenciaturas\n2.Ingenierías\n3.Ciencias de la Salud\nIngrese una opcion"));
               }
               switch (op) {
                   case 1:
                       tc="Licenciaturas";
                       op2=Integer.parseInt(JOptionPane.showInputDialog("1.Finanzas,\n2.Derecho,\n3.Administración de Empresas, \n4.Diseño Gráfico \n5.Mercadotecnia\nIngrese una opcion"));
                       while (op2>5 || op2<=0) {
                           op2=Integer.parseInt(JOptionPane.showInputDialog("1.Finanzas,\n2.Derecho,\n3.Administración de Empresas, \n4.Diseño Gráfico \n5.Mercadotecnia\nIngrese una opcion")); 
                       }
                       switch (op2) {
                           case 1:
                               
                               carrera="Finanzas";
                               break;
                           case 2:
                               carrera="Derecho";
                               break;
                           case 3:
                               carrera="Administración de Empresas";
                               break;
                           case 4:
                               carrera="Diseño Gráfico";
                               break;
                           case 5:
                               carrera="Mercadotecnia";
                               break;
                           default:
                               JOptionPane.showMessageDialog(null, "Dato no valido");
                               break;
                       }
                       break;
                   case 2:
                        tc="Ingenierías";
                        op2=Integer.parseInt(JOptionPane.showInputDialog("1. Sistemas Computacionales\n2.Industrial y de Sistemas\n3.Mecatrónica\n4. Biomédica y Energía\nIngrese una opcion"));
                        while (op2>4 || op2<=0) {
                           op2=Integer.parseInt(JOptionPane.showInputDialog("1. Sistemas Computacionales\n2.Industrial y de Sistemas\n3.Mecatrónica\n4. Biomédica y Energía\nIngrese una opcion"));
                       }
                       
                       switch (op2) {
                           case 1:
                               carrera="Sistemas Computacionales";
                               break;
                           case 2:
                               carrera="Industrial y de Sistemas";
                               break;
                           case 3:
                               carrera="Mecatronica";
                               break;
                           case 4:
                               carrera=" Biomédica y Energia";
                           default:
                               JOptionPane.showMessageDialog(null, "Dato no valido");
                               break;
                       }
                       break;
                   case 3:
                       tc="Ciencias de la Salud";
                       op2=Integer.parseInt(JOptionPane.showInputDialog("1. Medicina y Cirugía\n2.Odontología\n3.Nutrición y Terapia Físic\n4.Ocupacional\nIngrese una opcion"));
                       while (op2>4 || op2<=0) {
                           op2=Integer.parseInt(JOptionPane.showInputDialog("1. Medicina y Cirugía\n2.Odontología\n3.Nutrición y Terapia Físic\n4.Ocupacional\nIngrese una opcion"));
                       }
                     
                       switch (op2) {
                           case 1:
                               carrera="Medicina y Cirugia";
                               break;
                           case 2:
                               carrera="Odontologia";
                               break;
                           case 3:
                               carrera="Nutricion y Terapia Fisica";
                               break;
                           case 4:
                               carrera="Ocupacional";
                               break;
                           default:
                               JOptionPane.showMessageDialog(null, "Dato no valido");
                               break;
                       }
                       break;
                       
                   default:
                       JOptionPane.showMessageDialog(null, "Dato no valido");
                       break;
               }
               val=false;
           }
           catch(Exception e )
           {
              JOptionPane.showMessageDialog(null, "Ocurrio un error");
           }
          
       }
       DefaultListModel modelo
                = (DefaultListModel) Estudiantes.getModel();

        modelo.addElement(new Estudiantes(nombre, apellido, carrera, edad, edad, genero,tc)
        );

        Estudiantes.setModel(modelo);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void EstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstudiantesMouseClicked
        // TODO add your handling code here:
        if(evt.isMetaDown())
        {
            if (Estudiantes.getSelectedIndex() >= 0) {
            DefaultTreeModel modeloARBOL
                    = (DefaultTreeModel) jTree2.getModel();
            DefaultMutableTreeNode raiz
                    = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            //obtener la persona a guardar
            DefaultListModel modeloLISTA
                    = (DefaultListModel) Estudiantes.getModel();
            String Carrera, nombre,tipo,tc;
            int edad; 
            
            Carrera
                    = ((Estudiantes) modeloLISTA.get(
                            Estudiantes.getSelectedIndex())).
                    getCarrera();

            nombre = ((Estudiantes) modeloLISTA.get(
                    Estudiantes.getSelectedIndex())).
                    getNombre();
            edad = ((Estudiantes) modeloLISTA.get(
                    Estudiantes.getSelectedIndex())).
                    getEdad();
            tc= ((Estudiantes) modeloLISTA.get(
                            Estudiantes.getSelectedIndex())).
                    getTc();
            int centinela = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().
                        equals(Carrera)) {
                    DefaultMutableTreeNode p
                            = new DefaultMutableTreeNode(
                                    new Estudiantes(nombre, Carrera, edad)
                            );
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                    centinela = 1;
                } //fin if
                if (raiz.getChildAt(i).toString().
                        equals(tc)) {
                    DefaultMutableTreeNode p
                            = new DefaultMutableTreeNode(
                                    new Estudiantes(nombre, tc, edad)
                            );
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                    centinela = 2;
                }
            } //fin for  
            
            if (centinela == -1) {
                DefaultMutableTreeNode no
                        = new DefaultMutableTreeNode(tc);
                DefaultMutableTreeNode n
                        = new DefaultMutableTreeNode(Carrera);
                DefaultMutableTreeNode p
                        = new DefaultMutableTreeNode(
                                new Estudiantes(nombre, Carrera, edad)
                        );
                no.add(n);
                n.add(p);
                raiz.add(no);
            }
            if(centinela == 2)
            {
               DefaultMutableTreeNode no
                        = new DefaultMutableTreeNode(tc);
                DefaultMutableTreeNode n
                        = new DefaultMutableTreeNode(Carrera);
                DefaultMutableTreeNode p
                        = new DefaultMutableTreeNode(
                                new Estudiantes(nombre, Carrera, edad)
                        );
                no.add(n);
                n.add(p);
                raiz.add(no);
            }
            
            // fin if          
            modeloARBOL.reload();
            
        } else {
            JOptionPane.showMessageDialog(this,
                    "No hay persona seleccionada");
        }
        }
    }//GEN-LAST:event_EstudiantesMouseClicked

    private void jTree2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree2MouseClicked
        // TODO add your handling code here:
        if(evt.isMetaDown())
        {
            int row = jTree2.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            //marcar selecciondo
            
           jTree2.setSelectionRow(row);
            Object v1
                    = jTree2.getSelectionPath().
                    getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
                                  //regresa el tipo
            if (nodo_seleccionado.getUserObject() instanceof Estudiantes) {
                persona_seleccionada
                        = (Estudiantes) nodo_seleccionado.
                        getUserObject();
                menu_popup.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
            
        }
    }//GEN-LAST:event_jTree2MouseClicked

    private void ElimniarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElimniarActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(
                this,
                "Seguro de Eliminar?",
                "Confirm",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.OK_OPTION) {
            DefaultTreeModel m
                    = (DefaultTreeModel)jTree2.getModel();
            m.removeNodeFromParent(
                    nodo_seleccionado);
            m.reload();
        }
    }//GEN-LAST:event_ElimniarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        ad_Maestro.setModal(true);
        //Acoplacar tamaño de la ventana
        ad_Maestro.pack();
        //Alinear con respecto al padre
        ad_Maestro.setLocationRelativeTo(this);
        
        ad_Maestro.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo
                = (DefaultListModel) lMaestros.getModel();

        modelo.addElement(new Maestros(nombre.getText(), apellido.getText(),Integer.parseInt(sal.getText()),(Integer) sp_edad.getValue())
        );
        
        lMaestros.setModel(modelo);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo
                = (DefaultListModel) Clases.getModel();

        modelo.addElement(new Clases(nombre1.getText(), secion.getText(), (Integer)ed.getValue(),(Integer)salon.getValue(), true)
        );
        
        Clases.setModel(modelo);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        ad_clases.setModal(true);
        //Acoplacar tamaño de la ventana
        ad_clases.pack();
        //Alinear con respecto al padre
        ad_clases.setLocationRelativeTo(this);
        
        ad_clases.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void lMaestrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMaestrosMouseClicked
        // TODO add your handling code here:
        if(evt.isMetaDown())
        {  
          menu_MAE.show(evt.getComponent(), getX(), getY());
        }
    }//GEN-LAST:event_lMaestrosMouseClicked

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo
                = (DefaultListModel) lMaestros.getModel();

       modelo.remove(lMaestros.getSelectedIndex());
        
        lMaestros.setModel(modelo);
    }//GEN-LAST:event_EliminarActionPerformed

    private void ClasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClasesMouseClicked
        // TODO add your handling code here:
        if(evt.isMetaDown())
        {  
          mcla.show(evt.getComponent(), getX(), getY());
        }
    }//GEN-LAST:event_ClasesMouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
         DefaultListModel modelo
                = (DefaultListModel) Clases.getModel();

       modelo.remove(Clases.getSelectedIndex());
        
        Clases.setModel(modelo);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Clases;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Elimniar;
    private javax.swing.JList<String> Estudiantes;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JDialog ad_Maestro;
    private javax.swing.JDialog ad_clases;
    private javax.swing.JTextField apellido;
    private javax.swing.JSpinner ed;
    private javax.swing.JMenuItem gfd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTree jTree2;
    private javax.swing.JList<String> lMaestros;
    private javax.swing.JPopupMenu mcla;
    private javax.swing.JPopupMenu menu_MAE;
    private javax.swing.JPopupMenu menu_popup;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField sal;
    private javax.swing.JSpinner salon;
    private javax.swing.JTextField secion;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables
  ArrayList<Estudiantes> estu = new ArrayList();
    ArrayList<Maestros> maestr = new ArrayList();
    DefaultMutableTreeNode nodo_seleccionado;
    Estudiantes persona_seleccionada;
    Maestros persona2_seleccionada;
}
